version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 256m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  cambio:
    build: microservices/cambio-service
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker